# Generated by Django 5.1.1 on 2024-10-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Makanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_makanan', models.CharField(max_length=1000)),
                ('deskripsi_makanan', models.CharField(max_length=1000)),
                ('kategori_makanan', models.CharField(max_length=1000)),
                ('daftar_alergi', models.CharField(max_length=1000)),
            ],
        ),
    ]
