# Generated by Django 5.1.1 on 2024-10-25 03:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards_makanan', '0002_makanan_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makanan',
            name='daftar_alergi',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='makanan',
            name='deskripsi_makanan',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='makanan',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='makanan',
            name='kategori_makanan',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='makanan',
            name='nama_makanan',
            field=models.CharField(max_length=200),
        ),
    ]
