# Generated by Django 5.1 on 2024-10-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards_makanan', '0006_alter_menuitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='meal_type',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
