# Generated by Django 5.1 on 2024-10-26 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards_makanan', '0005_makanan'),
        ('cards_makanan', '0006_auto_20241026_1554'),
    ]

    operations = [
    ]
