# Generated by Django 5.1 on 2024-10-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards_makanan', '0007_menuitem_meal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
