# Generated by Django 5.1 on 2024-10-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards_makanan', '0008_restaurant_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image_url_menu',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
