# Generated by Django 5.1.2 on 2024-10-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_souvenir', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='souvenirentry',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
