# Generated by Django 5.1.2 on 2024-10-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_souvenir', '0002_alter_souvenirentry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='souvenirentry',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
