# Generated by Django 5.1.2 on 2024-10-26 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_souvenir', '0003_alter_souvenirentry_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='souvenirentry',
            name='user',
        ),
    ]
