# Generated by Django 5.1.2 on 2024-10-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_souvenir', '0004_remove_souvenirentry_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='souvenirentry',
            name='image',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
