# Generated by Django 5.1.2 on 2024-10-24 10:45

import django.db.models.deletion
import editors_choice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editors_choice', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorchoice',
            name='week',
            field=models.DateField(default=editors_choice.models.get_start_of_current_week),
        ),
        migrations.RemoveField(
            model_name='editorchoice',
            name='food_items',
        ),
        migrations.AlterField(
            model_name='foodrecommendation',
            name='food_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.fooditem'),
        ),
        migrations.AddField(
            model_name='editorchoice',
            name='food_items',
            field=models.ManyToManyField(to='editors_choice.foodrecommendation'),
        ),
    ]
