# Generated by Django 5.1.2 on 2024-10-25 03:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editors_choice', '0003_alter_foodrecommendation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorchoice',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
