# Generated by Django 5.1.2 on 2024-11-03 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards_makanan', '0009_menuitem_image_url_menu'),
        ('editors_choice', '0004_alter_editorchoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrecommendation',
            name='food_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cards_makanan.menuitem'),
        ),
    ]
