# Generated by Django 5.1.2 on 2024-11-22 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editors_choice', '0005_alter_foodrecommendation_food_item'),
        ('main', '0002_fooditem_food_type_alter_fooditem_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrecommendation',
            name='food_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.fooditem'),
        ),
    ]
