# Generated by Django 5.1.2 on 2024-12-02 06:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editors_choice', '0007_alter_foodrecommendation_food_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='foodrecommendation',
            name='rated_description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='FoodComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editors_choice.foodrecommendation')),
            ],
        ),
    ]
