# Generated by Django 5.1.2 on 2024-12-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editors_choice', '0008_foodrecommendation_rated_description_foodcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodrecommendation',
            name='comment_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
