# Generated by Django 5.1.2 on 2024-12-17 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editors_choice', '0009_foodrecommendation_comment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcomment',
            name='author_uname',
            field=models.CharField(default='', editable=False, max_length=150),
        ),
        migrations.AddField(
            model_name='foodrecommendation',
            name='author_uname',
            field=models.CharField(default='', editable=False, max_length=150),
        ),
    ]
