# Generated by Django 5.1.2 on 2024-10-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards_makanan', '0008_restaurant_image_url'),
        ('manajemen_pesanan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='items',
            field=models.ManyToManyField(to='cards_makanan.menuitem'),
        ),
    ]
